### ISSUE TITLE
Text color in progress bar

### ISSUE THREAD

**Issue by eggjoystick** [luigifab/human-theme#8]
Love this theme, thanks for making it.
On the default brown theme, the text color inside the progress bar is black, which is not very legible against the brown progress bar. See screenshot.

Double edged sword though, because the portion of the progress bar that is not filled does need to be black or dark for legibility.

Is it possible for the text color to differ based on whether the progress bar is filled or unfilled?

![human-logout-black-text](https://user-images.githubusercontent.com/58571795/102720590-e5b31080-42ba-11eb-9384-c831f29f34b0.png)

**Comment by luigifab** [comment]
That's true, for now I didn't find a way to do that with GTK 3.

**Comment by luigifab** [comment]
Yesterday I saw that the text color is good in treeviews when line is selected:

![image](https://user-images.githubusercontent.com/31816829/120010528-8aa9e600-bfdd-11eb-9923-5264f933b43d.png)

The following CSS code fix progress bar text color only in treviews:
```css
treeview.view.progressbar {
	color: @theme_selected_fg;
}
```

**Comment by luigifab** [comment]
The double text color seems to work only? before GTK 3.8.

Ambiance theme with...
Ubuntu 11.10 - GTK 3.2 / Ubuntu 13.04 - GTK 3.6 / Ubuntu 13.10 - GTK 3.8 :
![image](https://user-images.githubusercontent.com/31816829/120078122-33277b00-c0ae-11eb-80da-d504ad03be7d.png) ![image](https://user-images.githubusercontent.com/31816829/120078133-43d7f100-c0ae-11eb-9582-649b09ca639f.png) ![image](https://user-images.githubusercontent.com/31816829/120078318-366f3680-c0af-11eb-878d-f21b181380fe.png)

Edit: I started to create [appearance__progress_text.gtk3.patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e)  for this problem.

**Comment by luigifab** [comment]
Styles added in v2.0.0... but [the patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e#file-appearance__progress_text-patch) is not ready/working for now.

**Comment by luigifab** [comment]
Now fixed with the previous patch **for gtk3-classic**.
Automatic width/height and position of the text are not working without CSS, but for now it's ok for me.

![surprise](https://github.com/luigifab/human-theme/assets/31816829/a5b39874-dc6d-44b4-b520-46f20decaaa5)

Will be available in v2.2.0, without debug colors.

**Comment by luigifab** [comment]
Fixed in v2.2.0 with [appearance__progress_text.gtk3.patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e) for [gtk3-classic](https://build.opensuse.org/package/show/home:luigifab/gtk3-classic).
_In real life, this isn't really true, because the height of the progress bar is defined with CSS and not by text height._

**Comment by luigifab** [comment]
Fixed in v2.3.0 with [appearance__progress_text.gtk3.patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e) for [gtk3-classic](https://build.opensuse.org/package/show/home:luigifab/gtk3-classic).
_Now the height of the progress bar comes from the height of the text._

Fixed in v2.3.0 with [appearance__progress_text.gtk4.patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e) for [gtk4-classic](https://build.opensuse.org/package/show/home:luigifab/gtk4-classic).
_In real life, this isn't really true, because the height of the progress bar is defined with CSS and not by text height._

[readme](https://github.com/lah7/gtk3-classic/issues/58#issuecomment-2751060971)
